config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'applicants', to: "properties#all"
  resources :properties do
  	resources :applicants
  end
  resources :landlords
  root 'properties#index'
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  belongs_to :property
  validates :applicant_ssn, :applicant_name, :applicant_phone_number, :applicant_email, :applicant_birthdate, presence: true
  validates :applicant_ssn, format: { with: /\d{3}-\d{2}-\d{4}/, message: "Social Security number must be in the xxx-xx-xxxx format." }
  validates :applicant_phone_number, format: { with: /\d{3}-\d{3}-\d{4}/, message: "Phone number must be in the xxx-xxx-xxxx format." }
  validates :applicant_email, format: { with: URI::MailTo::EMAIL_REGEXP } 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/landlord.rb
class Landlord < ApplicationRecord
	has_many :properties, dependent: :destroy
	validates :landlord_name, :landlord_phone_number, presence: true
	validates :landlord_phone_number, format: { with: /\d{3}-\d{3}-\d{4}/, message: "must be in the xxx-xxx-xxxx format" }
end

app/models/property.rb
class Property < ApplicationRecord
	belongs_to :landlord
	has_many :applicants, dependent: :destroy
	validates :property_address, :monthly_rent, :image, presence: true
	validates :property_address, uniqueness: {case_sensitive: false}
	validates :monthly_rent, numericality: {greater_than_or_equal_to: 0}
	has_attached_file :image, styles: { medium: "400x300#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
	before_action :find_property
	def create
		@applicant = @property.applicants.create(applicant_params)
		  if @applicant.save
		    redirect_to property_path(@property), notice: 'Successfully Submitted New Application.'
		  else
		  	flash[:error] = "The application could not be submitted. Please verify that none of the input 
		  	fields are blank. The social security number must be in the xxx-xx-xxxx format and the phone 
		  	number must be in the xxx-xxx-xxxx format."
		    redirect_to property_path(@property)
		  end
	end
	def edit
 	   @applicant = @property.applicants.find(params[:id])
	end
	def update
		@applicant = @property.applicants.find(params[:id])
		if @applicant.update(applicant_params)
			redirect_to property_path(@property)
		else
			render 'edit'
		end
	end
	def destroy
		@applicant = @property.applicants.find(params[:id])
		@applicant.destroy
		redirect_to property_path(@property)
	end

	private
	def applicant_params
		params[:applicant].permit(:applicant_ssn,:applicant_name,:applicant_phone_number,:applicant_birthdate,:applicant_email)
	end
	def find_property
		@property=Property.find(params[:property_id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
	before_action :find_landlord, only: [:show,:edit,:update,:destroy]

	def index
		@landlord = Landlord.all.order('landlord_name ASC')
	end
	def show
	end
	def new
		@landlord = Landlord.new
	end
	def create
		@landlord = Landlord.new(landlord_params)
		if @landlord.save
			redirect_to @landlord, notice: "Successfully Created New Landlord"
		else
			render 'new'
		end
	end
	def edit
	end
	def update
		if @landlord.update(landlord_params)
			redirect_to @landlord
		else
			render 'edit'
		end
	end
	def destroy
		@landlord.destroy
		redirect_to landlords_path, notice: "Successfully Deleted Landlord"
	end

	private 
	def find_landlord
		@landlord = Landlord.find(params[:id])
	end
	def landlord_params
		params.require(:landlord).permit(:landlord_name, :landlord_phone_number)
	end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	before_action :find_property, only: [:show,:edit,:update,:destroy]
	def all
		@records = Property.joins(:landlord, :applicants).select("landlords.landlord_name, properties.property_address, applicants.applicant_name, applicants.applicant_ssn").where("landlords.id = properties.landlord_id AND properties.id=applicants.property_id")
	end
	def index
		@property = Property.all.order("created_at DESC")
	end
	def show
	end
	def new
		@property = Property.new
	end
	def create
		@property = Property.new(property_params)
		if @property.save
			redirect_to @property, notice: "Successfully Created New Property"
		else
			render 'new'
		end
	end
	def edit
	end
	def update
		if @property.update(property_params)
			redirect_to @property
		else
			render 'edit'
		end
	end
	def destroy
		@property.destroy
		redirect_to root_path, notice: "Successfully Deleted Property"
	end

	private 
	def find_property
		@property = Property.find(params[:id])
	end
	def property_params
		params.require(:property).permit(:property_address, :description, :monthly_rent, :image, :landlord_id)
	end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/applicants/_applicant.html.erb
<div class="container">
	<div class="card" id="applicant_info">
  		<div class="card-header">
   	 		<h2> <b><%= applicant.applicant_name %></b>
   	 			<%= link_to '<i class="material-icons">delete</i>'.html_safe, [applicant.property,applicant], method: :delete, style: 'color:#1A2930; padding-left:10px;', class: "float-right"%>
				  <%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_property_applicant_path(applicant.property,applicant), style: 'color:#1A2930;', class: "float-right"%>
   	 		</h2> 
  		</div>
  		<ul class="list-group list-group-flush">
  			<li class="list-group-item"> <b> Social Security Number: </b> <%= applicant.applicant_ssn %></li>
		    <li class="list-group-item"> <b> Phone Number: </b> <%= applicant.applicant_phone_number %></li>
		    <li class="list-group-item"> <b> Email: </b> <%= applicant.applicant_email %></li>
		    <li class="list-group-item"> <b> Birthdate: </b> <%= applicant.applicant_birthdate %></li>
  		</ul>
	</div>
</div>

app/views/applicants/_form.html.erb
<div class="container" style ='background-color: #C5C1C0; padding: 20px; border-radius: 7px; margin-top:30px; margin-bottom:30px;'>
	<h2 class="title is-4 bold">Rental Application Form</h2>
	<%= simple_form_for([@property, @property.applicants.build]) do |applicant| %>
		<form>
			<div class="form-group">
				<label>Social Security Number</label>
				<%= applicant.input :applicant_ssn, required:false, label:false, input_html:{class: "form-control"}%>
			</div>
			<div class="form-group">
				<label>Name</label>
				<%= applicant.input :applicant_name, required:false, label:false, input_html:{class: "form-control"}%>
			</div>
			<div class="form-group">
				<label>Birthdate</label>
				<span class="form-control" type="date"><%= applicant.date_field :applicant_birthdate, required:false, label:false, id: "picker" %></span>
			</div>
			<div class="form-group">
				<label>Phone Number</label>
				<%= applicant.input :applicant_phone_number, required:false, label:false, input_html:{class: "form-control"}%>
			</div>
			<div class="form-group">
				<label>Email Address</label>
				<%= applicant.input :applicant_email, required:false, label:false, input_html:{class: "form-control"}%>
			</div>

			<%= applicant.submit 'Submit', class: 'btn btn-warning', style: 'margin-top: 10px; width: 100px; font-size: 1.15em;'%>
			<%= applicant.button :button, "Cancel", type: "reset", class: "btn-outline-secondary", style: 'margin-top: 10px; width: 100px; font-size: 1.15em;' %>
		</form>
	<% end %>
</div>

app/views/applicants/edit.html.erb
<div class="container" style ='background-color: #C5C1C0; padding: 20px; border-radius: 7px; margin-top:30px;'>
	<h2 class="title is-4 bold">Edit Application Form
		<%= link_to '<i class="material-icons">arrow_back_ios</i>'.html_safe, property_path(@property),  style: 'color:#000;', class: "float-right" %> 
	</h2>
	<%= simple_form_for([@property, @applicant]) do |applicant| %>
		<form>
			<div class="form-group">
				<label>Social Security Number</label>
				<%= applicant.input :applicant_ssn, required:false, label:false, input_html:{class: "form-control"}%>
			</div>
			<div class="form-group">
				<label>Name</label>
				<%= applicant.input :applicant_name, required:false, label:false, input_html:{class: "form-control"}%>
			</div>
			<div class="form-group">
				<label>Birthdate</label>
				<span class="form-control" type="date"><%= applicant.date_field :applicant_birthdate, required:false, label:false, id: "picker" %></span>
			</div>
			<div class="form-group">
				<label>Phone Number</label>
				<%= applicant.input :applicant_phone_number, required:false, label:false, input_html:{class: "form-control"}%>
			</div>
			<div class="form-group">
				<label>Email Address</label>
				<%= applicant.input :applicant_email, required:false, label:false, input_html:{class: "form-control"}%>
			</div>

			<%= applicant.submit 'Submit', class: 'btn btn-warning', style: 'margin-top: 10px; width: 100px; font-size: 1.15em;'%>
		</form>
	<% end %>
	
</div>

app/views/landlords/_form.html.erb
<div class="container" style ='background-color: #C5C1C0; padding: 20px; border-radius: 7px; margin-top:30px; margin-bottom:30px;'>
	<h2 class="title is-4 bold">Landlord Registration Form</h2>
	<%= simple_form_for @landlord, html: {multipart: true} do |landlord| %>
		
		<% if @landlord.errors.any? %>
			<div class = "errors">
				<ul>
					<% @landlord.errors.full_messages.each do |message| %>
						<p class = "alert alert-danger" role="alert"><%= message %></p>
					<% end %>
				</ul>
			</div>
		<% end %>
		
		<form>
			
			<div class="form-group">
				<label>Landlord Name</label>
				<%= landlord.input :landlord_name, required:false, label:false, input_html:{class: "form-control"}%>
			</div>
				<div class="form-group">
				<label>Landlord Phone Number</label>
				<%= landlord.input :landlord_phone_number, required:false, label:false, input_html:{class: "form-control"}%>
			</div>

			<%= landlord.submit 'Submit', class: 'btn btn-warning', style: 'margin-top: 10px; width: 100px; font-size: 1.15em;'%>
			<%= landlord.button :button, "Cancel", type: "reset", class: "btn-outline-secondary", style: 'margin-top: 10px; width: 100px; font-size: 1.15em;' %>
		</form>
		

	<% end %>
</div>

app/views/landlords/edit.html.erb
<%= render 'form' %>

app/views/landlords/index.html.erb
<div class="container">
	<div class="jumbotron">
		<h1 class="display-4">There's no place like Homestead.</h1>
		<p class="lead">Homestead is an online rental property management system. It stores tenant application forms for real estate registered with the company.</p>
		<hr class="my-4">
		<p>Register as a landlord in order to manage property on this platform.</p>
		<p class="lead">
		<%= link_to "Click here to register a new Landlord",new_landlord_path, class:"btn btn-warning btn-lg" %> 
		</p>
    </div>
    <% if Landlord.any? %>
	    <div class="list-group" id="list-group-landlord">
		<% @landlord.each do |landlord| %>
			<li class="list-group-item">
				<%= link_to landlord.landlord_name, landlord %>
			</li>
		<% end %>
		</div>
	<% end %>	
</div>
<br>

app/views/landlords/new.html.erb
<%= render 'form' %>

app/views/landlords/show.html.erb
<div class="container" style="vertical-align: middle;">
	<div class="card mx-auto" id="landlord-card">
		<div class="card-header">
			<h1 class="card-title"> <b><%=@landlord.landlord_name%></b>
				<%= link_to '<i class="material-icons">delete</i>'.html_safe,landlord_path, method: :delete, style: 'color:#1A2930; padding-left:10px; padding-top:10px;', class: "float-right" %>
				<%= link_to '<i class="material-icons">edit</i>'.html_safe,edit_landlord_path, style: 'color:#1A2930; padding-top:10px;', class: "float-right" %> 
			</h1>
		</div>
		<div class="card-body">
			<p> You can contact me at (US) <%=@landlord.landlord_phone_number%>. </p>
		</h5>
	</div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homestead</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300&display=swap' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Bebas+Neue|Kaushan+Script|Lato|Open+Sans&display=swap" rel="stylesheet' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet' %>
     <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-expand-lg">
      <div class="navbar-brand">Homestead</div>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <div id="hell"> <%= link_to "Properties",root_path, class: 'navbar-item' %> </div>
          </li>
          <li class="nav-item">
            <%= link_to " Landlords", landlords_path, class: 'navbar-item' %>
          </li>
          <li class="nav-item">
            <%= link_to " Applicants", applicants_path, class: 'navbar-item' %>
          </li>
        </ul>
    </nav>

    <br>

    <div class="container">
      <% flash.each do |type, message| %>
        <% if type=="notice" %>
          <div class="alert alert-secondary" role="alert">
            <%= message %>
          </div>
        <% else %>
          <div class="alert alert-danger" role="alert">
            <%= message %>
          </div>
        <% end %>
      <% end %>
    </div>

    <%= yield %>


  </body>
</html>

app/views/properties/_form.html.erb
<div class="container" style ='background-color: #C5C1C0; padding: 20px; border-radius: 7px; margin-top:30px; margin-bottom:30px;'>
	<h2 class="title is-4 bold">Property Listing Form</h2>
	<%= simple_form_for @property, html: {multipart: true} do |property| %>
		
	 	<% if @property.errors.any? %>
			<div class = "errors">
				<ul>
					<% @property.errors.full_messages.each do |message| %>
					<p class = "alert alert-danger" role="alert"><%= message %></p>
					<% end %>
				</ul>
			</div>
		<% end %> 
		
		<form>
			<div class="form-group">
				<label>Property Address</label>
				<%= property.input :property_address, required:false, label:false, input_html:{class: "form-control"}%>
			</div>

			<div class="form-group">
				<label>Monthly Rent</label>
				<%= property.input :monthly_rent, required:false, label:false, input_html:{class: "form-control", id:"with-prepend"}%>
			</div>

			<div class="form-group">
				<label>Description</label>
				<%= property.input :description, required:false, label:false, input_html:{class: "form-control", rows:"5", id:"propertyDescription"}%>
			</div>

			<div class="form-group" id="fileUpload">
				<label>Property Image</label> <br>
				<label for="file-upload" class="custom-file-upload">
					<i class="material-icons">get_app</i> Choose File
				</label>
				<%= property.input :image, required:false, label:false, input_html:{class: "form-control-file", type: "file", id: "file-upload"}%>
			</div>

			<div class="form-group">
				<label>Landlord</label>
				<%= collection_select(:property, :landlord_id, Landlord.all, :id, :landlord_name, { :multiple => false}, {:class => 'form-control'}) %>
			</div>

			<%= property.submit 'Submit', class: 'btn btn-warning', style: 'margin-top: 10px; width: 100px; font-size: 1.15em;'%>
			<%= property.button :button, "Cancel", type: "reset", class: "btn-outline-secondary", style: 'margin-top: 10px; width: 100px; font-size: 1.15em;' %>

		</form>

	<% end %>
</div>

app/views/properties/all.html.erb
<div class="container">
	<div class="card" id="table-card">
		<table class="table">
			<thead>
			    <tr>
			      <th scope="col">Applicant Name</th>
			      <th scope="col">Applicant SSN</th>
			      <th scope="col">Property Address</th>
			      <th scope="col">Landlord Name</th>
			    </tr>
			</thead>
			<tbody>
				<% @records.each do |record| %>
					<tr>
						<td><%= record.applicant_name %></td>
						<td><%= record.applicant_ssn %></td>
						<td><%= record.property_address %></td>
						<td><%= record.landlord_name %></td>
					</tr>	
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/properties/edit.html.erb
<%= render 'form' %>

app/views/properties/index.html.erb
<div class="container">
	
	 <div class="jumbotron">
		<h1 class="display-4">There's no place like Homestead.</h1>
		<p class="lead">Homestead is an online rental property management system. It stores tenant application forms for real estate registered with the company.</p>
		<hr class="my-4">
		<p>List your property and accept applications from our users.</p>
		<p class="lead">
		<%= link_to "Click here to add a new property",new_property_path, class:"btn btn-warning btn-lg" %> 
		</p>
    </div>

	<% @property.each_slice(2) do |property| %>
		<div class="row" >
			<% property.each do |property| %>
				<div class="col-md-6">
					<div class="hovereffect">
						<%= link_to property do%>
							<%= image_tag property.image.url(:medium), class: 'img-responsive'%>
							<div class="overlay">
								<h2><%= property.property_address %></h2>
								<p><b><%= property.landlord.landlord_name %></b></p>
							</div>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/properties/new.html.erb
<%= render 'form' %>

app/views/properties/show.html.erb
<div class="container">
	<div class="row">
		<%= image_tag @property.image.url(:medium), class: "property_image"%>
		<div class="card col" id="property_info">
			<div class="card-header" id="card_header">
				<h2><%=@property.property_address%>
				<%= link_to '<i class="material-icons">delete</i>'.html_safe, property_path, method: :delete, style: 'color:#FFFFFF; padding-left:10px;', class: "float-right"%>
				<%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_property_path, style: 'color:#FFFFFF;', class: "float-right"%>
				</h2>
			</div>
			<div class="card-body align-items-center">
				<p> 
				<b>$ </b><%=@property.monthly_rent%> / month | 
				<%= link_to @property.landlord.landlord_name, landlord_path(@property.landlord.id), style: 'color:#fff;' %>
				</p>
				<p><%=@property.description%></p>
			</div>
		</div>
	</div>
	<div class="row">
		 
	</div>

</div> 

<%= render @property.applicants %>
<%= render "applicants/form" %>